version: '3.8' 
# the attribute version is obsolete
services:
  app:
    build:
      context: .
    ports:
      - "7860:7860" 
    env_file:
      - .env
    command: ["python", "app.py"]

  tests:
    build:
      context: .
    command: ["pytest", "tests/"]  
    
